// Creations Actions Popular

export const FETCH_CREATIONS_LOADING = 'FETCH_CREATIONS_LOADING'
export const FETCH_CREATIONS_SUCCESS = 'FETCH_CREATIONS_SUCCESS'
export const FETCH_CREATIONS_FAIL = 'FETCH_CREATIONS_FAIL'
export const CLEAR_CREATIONS = 'CLEAR_CREATIONS'

// Creations Actions Latest

export const FETCH_CREATIONS_LATEST_LOADING = 'FETCH_CREATIONS_LATEST_LOADING'
export const FETCH_CREATIONS_LATEST_SUCCESS = 'FETCH_CREATIONS_LATEST_SUCCESS'
export const FETCH_CREATIONS_LATEST_FAIL = 'FETCH_CREATIONS_LATEST_FAIL'
export const CLEAR_CREATIONS_LATEST = 'CLEAR_CREATIONS_LATEST'

// Creations Actions Feed

export const FETCH_CREATIONS_FEED_LOADING = 'FETCH_CREATIONS_FEED_LOADING'
export const FETCH_CREATIONS_FEED_SUCCESS = 'FETCH_CREATIONS_FEED_SUCCESS'
export const FETCH_CREATIONS_FEED_FAIL = 'FETCH_CREATIONS_FEED_FAIL'
export const CLEAR_CREATIONS_FEED = 'CLEAR_CREATIONS_FEED'

// Creations Details Actions

export const FETCH_CREATION_DETAILS_LOADING = 'FETCH_CREATION_DETAILS_LOADING'
export const FETCH_CREATION_DETAILS_SUCCESS = 'FETCH_CREATION_DETAILS_SUCCESS'
export const FETCH_CREATION_DETAILS_FAIL = 'FETCH_CREATION_DETAILS_FAIL'

// Creations User Specific Actions

export const FETCH_USER_CREATIONS_LOADING = 'FETCH_USER_CREATIONS_LOADING'
export const FETCH_USER_CREATIONS_SUCCESS = 'FETCH_USER_CREATIONS_SUCCESS'
export const FETCH_USER_CREATIONS_FAIL = 'FETCH_USER_CREATIONS_FAIL'
export const FETCH_USER_NEW_CREAIONS = 'FETCH_USER_NEW_CREAIONS'
export const FETCH_USER_NEW_CREAIONS_LOADING = 'FETCH_USER_NEW_CREAIONS_LOADING'
export const CLEAR_USER_CREAIONS = 'CLEAR_USER_CREAIONS'

// Auth Actions

export const FETCH_AUTH_LOADING = 'FETCH_AUTH_LOADING'
export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS'
export const FETCH_AUTH_FAIL = 'FETCH_AUTH_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN = 'USER_LOGIN'

// Register User

export const REGISTERING_USER = 'REGISTERING_USER'
export const REGISTERATION_SUCCESS = 'REGISTERATION_SUCCESS'
export const REGISTERATION_FAIL = 'REGISTERATION_FAIL'

// google Auth Actions
export const GOOGLE_AUTH_LOADING = 'GOOGLE_AUTH_LOADING'
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS'
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL'

// facebook Auth Actions
export const FACEBOOK_AUTH_LOADING = 'FACEBOOK_AUTH_LOADING'
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS'
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL'

// Fetch Refiq Actions

export const FETCH_REFIQ_LOADING = 'FETCH_REFIQ_LOADING'
export const FETCH_REFIQ_SUCCESS = 'FETCH_REFIQ_SUCCESS'
export const FETCH_REFIQ_FAIL = 'FETCH_REFIQ_FAIL'
export const CLEAR_REFIQS = 'CLEAR_REFIQS'

// Fetch Collections Actions

export const FETCH_COLLECTION_LOADING = 'FETCH_COLLECTION_LOADING'
export const CLEAR_COLLECTION_DATA = 'CLEAR_COLLECTION_DATA'
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS'
export const FETCH_COLLECTION_FAIL = 'FETCH_COLLECTION_FAIL'
export const FETCH_CREATION_OF_COLLECTION_LOADING = 'FETCH_CREATION_OF_COLLECTION_LOADING'
export const FETCH_CREATION_OF_COLLECTION_SUCCESS = 'FETCH_CREATION_OF_COLLECTION_SUCCESS'
export const FETCH_CREATION_OF_COLLECTION_FAIL = 'FETCH_CREATION_OF_COLLECTION_FAIL'

// Pusher related Actions

export const SUBSCRIBING_PUSHER_CHANNEL = 'SUBSCRIBING_PUSHER_CHANNEL'
export const SUBSCRIBE_PUSHER_CHANNEL = 'SUBSCRIBE_PUSHER_CHANNEL'
export const FAIL_TO_SUBSCRIBING_PUSHER_CHANNEL = 'FAIL_TO_SUBSCRIBING_PUSHER_CHANNEL'
export const GET_PUSHER_DATA = 'GET_PUSHER_DATA'
export const UPDATE_PUSHER_DATA = 'UPDATE_PUSHER_DATA'
export const UPDATE_POPLUAR_DATA = 'UPDATE_POPLUAR_DATA'
export const UPDATE_LATEST_DATA = 'UPDATE_LATEST_DATA'
export const UPDATE_FEED_DATA = 'UPDATE_FEED_DATA'
export const UPDATE_CREATIONS_DETAILS_DATA = 'UPDATE_CREATIONS_DETAILS_DATA'
export const UPDATE_USER_CREATIONS_DATA = 'UPDATE_USER_CREATIONS_DATA'
export const UPDATE_REFIQS_DATA = 'UPDATE_REFIQS_DATA'
export const UPDATE_CREATIONS_OF_COLLECTIONS_DATA = 'UPDATE_CREATIONS_OF_COLLECTIONS_DATA'

export const CONNECT_PUSHER_SUCCESSFULLY = 'CONNECT_PUSHER_SUCCESSFULLY'
export const CONNECTING_TO_PUSHER = 'CONNECTING_TO_PUSHER'

// Audio Player related Actions

export const OPEN_AUDIO_PLAYER = 'OPEN_AUDIO_PLAYER'
export const CLOSE_AUDIO_PLAYER = 'CLOSE_AUDIO_PLAYER'

// Categories related Actions

export const SELECTED_CATEGORIES = 'SELECTED_CATEGORIES'
export const SELECTED_SEARCH_CATEGORIES = 'SELECTED_SEARCH_CATEGORIES'
export const SELECTED_SEARCH_LOCATIONS = 'SELECTED_SEARCH_LOCATIONS'

// Search related Actions

export const SEARCHING = 'SEARCHING'
export const SEARCH_SUCCESS_CREATIONS = 'SEARCH_SUCCESS_CREATIONS'
export const SEARCH_SUCCESS_CREATORS = 'SEARCH_SUCCESS_CREATORS'
export const CLEAR_SEARCH_SUCCESS = 'CLEAR_SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'

// Creation Views related Actions

export const INCREASE_CREATION_VIEW_REQUEST = 'INCREASE_CREATION_VIEW_REQUEST'
export const INCREASE_CREATION_VIEW_FAIL = 'INCREASE_CREATION_VIEW_FAIL'
export const INCREASE_CREATION_VIEW_SUCCESS = 'INCREASE_CREATION_VIEW_SUCCESS'

// Notifications Actions

export const FETCH_NOTIFICATIONS_LOADING = 'FETCH_NOTIFICATIONS_LOADING'
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'
export const FETCH_NOTIFICATIONS_FAIL = 'FETCH_NOTIFICATIONS_FAIL'
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS'
export const HIDE_NOTIFICATION_BADGE = 'HIDE_NOTIFICATION_BADGE'

// Followers related Actions

export const FETCH_USER_FOLLOWERS_REQUEST = 'FETCH_USER_FOLLOWERS_REQUEST'
export const FETCH_USER_FOLLOWERS_FAIL = 'FETCH_USER_FOLLOWERS_FAIL'
export const FETCH_USER_FOLLOWERS_SUCCESS = 'FETCH_USER_FOLLOWERS_SUCCESS'
export const CLEAR_FOLLOWERS_LIST = 'CLEAR_FOLLOWERS_LIST'

// Followed related Actions

export const FETCH_USER_FOLLOWED_REQUEST = 'FETCH_USER_FOLLOWED_REQUEST'
export const FETCH_USER_FOLLOWED_FAIL = 'FETCH_USER_FOLLOWED_FAIL'
export const FETCH_USER_FOLLOWED_SUCCESS = 'FETCH_USER_FOLLOWED_SUCCESS'
